package player;

/**
 * Token types, generated by the Lexer and used by the Parser to determine the
 * correct processing strategy.
 * 
 */
public enum Type {
    /**
     * The Fields that belong to the Header.
     */
    FIELD_INDEX_NUMBER, FIELD_TITLE, FIELD_COMPOSER_NAME, FIELD_DEFAULT_LENGTH, FIELD_METER, FIELD_TEMPO, FIELD_KEY, FIELD_VOICE,

    /**
     * Digits. Name is actually a misnomer, as it represents 1 or more digits.
     */
    DIGIT,
    /**
     * A single note character
     */
    NOTE_LETTER,

    /**
     * An accidental, e.g., sharp, flat, or neutral.
     */
    ACCIDENTAL,
    /**
     * Any of the various barlines
     */
    BARLINE,
    /**
     * Alternative repeats (1st and 2nd only)
     */
    NTH_REPEAT,

    /**
     * Multinote, or Chord.
     */
    BEGIN_MULTINOTE, END_MULTINOTE,

    /**
     * Octave shift character, either up or down.
     */
    OCTAVE,
    /**
     * Fraction bar that is used in meter and note length specifications.
     */
    FRACTION_BAR,
    /**
     * Tuplet, series of notes that are played in rapid succession, with special
     * timing rules
     */
    TUPLET,

    /**
     * Comment. Should be discarded by all competent Lexers.
     */
    COMMENT,
    /**
     * End of file.
     */
    EOF
}
